export type { IContextTypes, IProviderTypes } from "../Context/contextTypes"
export type { IFooterLinksTypes } from "./FooterComponent/FooterLinks/footerLinksTypes"
export type { IFooterImagesTypes } from "./FooterComponent/FooterImages/footerImagesTypes"
export type { IHeaderButtonTypes } from "./HeaderComponent/HeaderButton/headerButtonTypes"
export type { IBasketTypes } from "./HeaderComponent/Basket/basketTypes"
export type { MealsCountParams, IHeaderTypes } from "./HeaderComponent/headerTypes"
export type { INutritionTypes } from "./MainComponent/Nutrition/nutritionTypes"
export type { IDescriptionTypes } from "./MainComponent/Description/descriptionTypes"
